# Generated by Django 3.0.3 on 2020-03-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_ID', models.IntegerField(max_length=250)),
                ('staff_Last_Name', models.CharField(max_length=250)),
                ('staff_First_Name', models.CharField(max_length=250)),
                ('staff_Street_Address', models.CharField(max_length=1024)),
                ('staff_City', models.CharField(max_length=1024)),
                ('staff_Zipcode', models.IntegerField(max_length=250)),
                ('staff_Email', models.EmailField(max_length=1024)),
                ('staff_Phone', models.IntegerField(max_length=1024)),
                ('staff_status', models.CharField(choices=[('1', 'Full Time'), ('2', 'Part Time'), ('3', 'Volunteer')], default='Fulltime', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.IntegerField(max_length=250)),
                ('student_Last_Name', models.CharField(max_length=250)),
                ('student_First_Name', models.CharField(max_length=250)),
                ('student_Date_of_Birth', models.DateField()),
                ('student_Gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('student_Street_Address', models.CharField(max_length=1024)),
                ('student_City', models.CharField(max_length=1024)),
                ('student_Zipcode', models.IntegerField(max_length=250)),
                ('student_Email', models.EmailField(max_length=1024)),
                ('student_Phone', models.IntegerField(max_length=1024)),
                ('student_School', models.CharField(max_length=1024)),
                ('student_Notes', models.CharField(max_length=1024)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMFK.Staff')),
            ],
        ),
    ]
