# Generated by Django 3.0.3 on 2020-03-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OMFK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('attendance', models.CharField(choices=[('1', 'PRESENT'), ('2', 'ABSENT'), ('3', 'LATE')], default='PRESENT', max_length=1024)),
                ('notes', models.CharField(max_length=1024)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMFK.Staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMFK.Student')),
            ],
        ),
    ]
